/**
 * Frequency table types — the data structure for GTO lookup tables.
 *
 * Each archetype has one FrequencyTable containing action frequencies
 * per hand category, for both IP and OOP positions.
 *
 * Pure TypeScript, zero Convex imports.
 */
import type { ArchetypeId } from "../archetypeClassifier";
import type { HandCategory } from "../handCategorizer";

// ═══════════════════════════════════════════════════════
// CORE TYPES
// ═══════════════════════════════════════════════════════

/** Standard GTO actions used in frequency tables */
export type GtoAction =
  | "fold"
  | "check"
  | "call"
  | "bet_small"    // ~33% pot
  | "bet_medium"   // ~66-75% pot
  | "bet_large"    // 100%+ pot (overbet)
  | "raise_small"
  | "raise_large";

/** Action frequencies for a single hand category: action → probability (0-1) */
export type ActionFrequencies = Partial<Record<GtoAction, number>>;

/** All hand category frequencies for one position */
export type PositionFrequencies = Partial<Record<HandCategory, ActionFrequencies>>;

export interface FrequencyTable {
  archetypeId: ArchetypeId;
  name: string;
  description: string;
  context: {
    street: "preflop" | "flop" | "turn" | "river";
    potType: "srp" | "3bet" | "4bet" | "bvb";
    heroPosition: string | string[];
    villainPosition: string | string[];
  };
  /** IP (in position) frequencies — hand category → action → frequency */
  ipFrequencies: PositionFrequencies;
  /** OOP (out of position) frequencies */
  oopFrequencies: PositionFrequencies;
  /** Available actions for IP */
  actionsIp: GtoAction[];
  /** Available actions for OOP */
  actionsOop: GtoAction[];
  /** Number of solver boards averaged (for postflop) */
  boardsAnalyzed?: number;
  /** One-line teaching principle */
  keyPrinciple: string;
  /** Common mistakes players make */
  commonMistakes: string[];
  /** Data provenance */
  source: string;
}

// ═══════════════════════════════════════════════════════
// FREQUENCY BANDS — variance across boards within an archetype
// ═══════════════════════════════════════════════════════

/**
 * Statistical distribution for a single action frequency across multiple boards.
 * Instead of a point estimate ("bet 55%"), shows the range ("bet 49-61%, avg 55%").
 *
 * The band width tells the user how board-specific the answer is:
 * - Narrow band (±3-5%): archetype approximation is very accurate
 * - Wide band (±15%+): board-specific details matter, answer is approximate
 */
export interface FrequencyBand {
  /** Average frequency across all solved boards */
  mean: number;
  /** Standard deviation — measures how tightly boards cluster */
  stdDev: number;
  /** Minimum frequency seen across any board */
  min: number;
  /** Maximum frequency seen across any board */
  max: number;
  /** How many boards contributed to this statistic */
  sampleCount: number;
}

/** Frequency bands for each action (replaces flat ActionFrequencies for band-aware tables) */
export type ActionFrequencyBands = Partial<Record<GtoAction, FrequencyBand>>;

/** Per-category band data for one position */
export type PositionFrequencyBands = Partial<Record<HandCategory, ActionFrequencyBands>>;

/**
 * Archetype accuracy metrics — how tightly the boards cluster.
 * Computed once during solver import, displayed in UI.
 */
export interface ArchetypeAccuracy {
  /** Average stdDev across all hand categories and actions (0-1, lower = tighter) */
  avgStdDev: number;
  /** Accuracy score: 1 - avgStdDev, clamped to [0, 1]. Higher = more accurate. */
  accuracy: number;
  /** Human label: "very high" (>0.95) | "high" (>0.90) | "moderate" (>0.80) | "approximate" */
  confidenceLabel: "very_high" | "high" | "moderate" | "approximate";
  /** Number of boards that contributed to this archetype */
  boardCount: number;
}

/**
 * Extended solver output format that includes per-board distributions.
 * Generated by the enhanced parse script (batch_solve.py parse --bands).
 */
export interface SolverOutputWithBands extends SolverOutput {
  /** Per-board frequency values (for computing bands in TypeScript) */
  ip_distributions?: Record<string, Record<string, number[]>>;
  oop_distributions?: Record<string, Record<string, number[]>>;
}

/**
 * Compute a FrequencyBand from an array of per-board frequency values.
 */
export function computeBand(values: number[]): FrequencyBand {
  if (values.length === 0) {
    return { mean: 0, stdDev: 0, min: 0, max: 0, sampleCount: 0 };
  }
  if (values.length === 1) {
    return { mean: values[0], stdDev: 0, min: values[0], max: values[0], sampleCount: 1 };
  }

  const n = values.length;
  const mean = values.reduce((a, b) => a + b, 0) / n;
  const variance = values.reduce((sum, v) => sum + (v - mean) ** 2, 0) / n;
  const stdDev = Math.sqrt(variance);
  const min = Math.min(...values);
  const max = Math.max(...values);

  return { mean, stdDev, min, max, sampleCount: n };
}

/**
 * Compute archetype accuracy from frequency bands.
 * Averages the stdDev across all categories and actions.
 */
export function computeArchetypeAccuracy(
  ipBands: PositionFrequencyBands,
  oopBands: PositionFrequencyBands,
  boardCount: number,
): ArchetypeAccuracy {
  const stdDevs: number[] = [];

  for (const bands of [ipBands, oopBands]) {
    for (const actionBands of Object.values(bands)) {
      if (!actionBands) continue;
      for (const band of Object.values(actionBands)) {
        if (band && band.sampleCount >= 2) {
          stdDevs.push(band.stdDev);
        }
      }
    }
  }

  const avgStdDev = stdDevs.length > 0
    ? stdDevs.reduce((a, b) => a + b, 0) / stdDevs.length
    : 0;

  const accuracy = Math.max(0, Math.min(1, 1 - avgStdDev));

  let confidenceLabel: ArchetypeAccuracy["confidenceLabel"];
  if (accuracy >= 0.95) confidenceLabel = "very_high";
  else if (accuracy >= 0.90) confidenceLabel = "high";
  else if (accuracy >= 0.80) confidenceLabel = "moderate";
  else confidenceLabel = "approximate";

  return { avgStdDev, accuracy, boardCount, confidenceLabel };
}

/**
 * Build band data from per-board distributions.
 */
export function buildPositionBands(
  distributions: Record<string, Record<string, number[]>>,
): PositionFrequencyBands {
  const result: PositionFrequencyBands = {};

  for (const [solverCat, actionDists] of Object.entries(distributions)) {
    const handCat = SOLVER_CATEGORY_MAP[solverCat];
    if (!handCat) continue;

    const bands: ActionFrequencyBands = {};
    for (const [action, values] of Object.entries(actionDists)) {
      const gtoAction = SOLVER_ACTION_MAP[action];
      if (gtoAction && values.length > 0) {
        bands[gtoAction] = computeBand(values);
      }
    }

    // Merge if category already exists (e.g. underpair + bottom_pair)
    if (result[handCat]) {
      const existing = result[handCat]!;
      for (const [action, band] of Object.entries(bands)) {
        const key = action as GtoAction;
        if (!existing[key]) {
          existing[key] = band;
        }
        // If both exist, we can't perfectly merge distributions — use weighted average
      }
    } else {
      result[handCat] = bands;
    }
  }

  return result;
}

/**
 * Convert SolverOutputWithBands to both a FrequencyTable and band data.
 */
export function solverOutputToTableWithBands(
  raw: SolverOutputWithBands,
  metadata: {
    name: string;
    description: string;
    keyPrinciple: string;
    commonMistakes: string[];
  },
): {
  table: FrequencyTable;
  ipBands: PositionFrequencyBands;
  oopBands: PositionFrequencyBands;
  accuracy: ArchetypeAccuracy;
} {
  const table = solverOutputToTable(raw, metadata);

  const ipBands = raw.ip_distributions
    ? buildPositionBands(raw.ip_distributions)
    : {};
  const oopBands = raw.oop_distributions
    ? buildPositionBands(raw.oop_distributions)
    : {};

  const accuracy = computeArchetypeAccuracy(ipBands, oopBands, raw.boardsAnalyzed);

  return { table, ipBands, oopBands, accuracy };
}

// ═══════════════════════════════════════════════════════
// BOARD TYPICALITY — how representative is THIS board of its archetype?
// ═══════════════════════════════════════════════════════

/**
 * Feature vector for a board, used to measure distance from archetype centroid.
 * All values normalized to 0-1 range.
 */
export interface BoardFeatures {
  /** Highest card rank normalized: 0 (deuce) to 1 (ace) */
  highCardNorm: number;
  /** Wetness score from analyzeBoard() (already 0-1) */
  wetness: number;
  /** 1 if paired, 0 if not */
  isPaired: number;
  /** 0 = rainbow, 0.5 = two-tone, 1 = monotone */
  suitedness: number;
  /** 1 if has connectors, 0 if not */
  connectivity: number;
}

/**
 * Archetype centroid — the "ideal" board features for this archetype.
 * Used to measure how typical a specific board is.
 */
export interface ArchetypeCentroid {
  archetypeId: ArchetypeId;
  center: BoardFeatures;
  /** Per-feature tolerance (how much variation is normal) */
  tolerance: BoardFeatures;
}

/**
 * Convert a BoardTexture (from analyzeBoard()) to normalized features.
 */
export function boardToFeatures(texture: {
  highCard: number;
  wetness: number;
  isPaired: boolean;
  isMonotone: boolean;
  isTwoTone: boolean;
  isRainbow: boolean;
  hasConnectors: boolean;
}): BoardFeatures {
  return {
    highCardNorm: texture.highCard / 12, // 0=2, 12=A → 0-1
    wetness: texture.wetness,
    isPaired: texture.isPaired ? 1 : 0,
    suitedness: texture.isMonotone ? 1 : texture.isTwoTone ? 0.5 : 0,
    connectivity: texture.hasConnectors ? 1 : 0,
  };
}

/** Expected centroid features for each flop texture archetype */
const ARCHETYPE_CENTROIDS: Partial<Record<ArchetypeId, { center: BoardFeatures; tolerance: BoardFeatures }>> = {
  ace_high_dry_rainbow: {
    center: { highCardNorm: 1.0, wetness: 0.15, isPaired: 0, suitedness: 0, connectivity: 0 },
    tolerance: { highCardNorm: 0.05, wetness: 0.15, isPaired: 0.1, suitedness: 0.1, connectivity: 0.3 },
  },
  kq_high_dry_rainbow: {
    center: { highCardNorm: 0.88, wetness: 0.2, isPaired: 0, suitedness: 0, connectivity: 0 },
    tolerance: { highCardNorm: 0.1, wetness: 0.15, isPaired: 0.1, suitedness: 0.1, connectivity: 0.3 },
  },
  mid_low_dry_rainbow: {
    center: { highCardNorm: 0.58, wetness: 0.2, isPaired: 0, suitedness: 0, connectivity: 0 },
    tolerance: { highCardNorm: 0.15, wetness: 0.15, isPaired: 0.1, suitedness: 0.1, connectivity: 0.3 },
  },
  paired_boards: {
    center: { highCardNorm: 0.5, wetness: 0.25, isPaired: 1, suitedness: 0.25, connectivity: 0.3 },
    tolerance: { highCardNorm: 0.4, wetness: 0.2, isPaired: 0.05, suitedness: 0.3, connectivity: 0.4 },
  },
  two_tone_disconnected: {
    center: { highCardNorm: 0.7, wetness: 0.45, isPaired: 0, suitedness: 0.5, connectivity: 0 },
    tolerance: { highCardNorm: 0.25, wetness: 0.2, isPaired: 0.1, suitedness: 0.1, connectivity: 0.3 },
  },
  two_tone_connected: {
    center: { highCardNorm: 0.6, wetness: 0.7, isPaired: 0, suitedness: 0.5, connectivity: 1 },
    tolerance: { highCardNorm: 0.25, wetness: 0.2, isPaired: 0.1, suitedness: 0.1, connectivity: 0.2 },
  },
  monotone: {
    center: { highCardNorm: 0.6, wetness: 0.85, isPaired: 0, suitedness: 1, connectivity: 0.3 },
    tolerance: { highCardNorm: 0.3, wetness: 0.15, isPaired: 0.1, suitedness: 0.05, connectivity: 0.4 },
  },
  rainbow_connected: {
    center: { highCardNorm: 0.55, wetness: 0.5, isPaired: 0, suitedness: 0, connectivity: 1 },
    tolerance: { highCardNorm: 0.25, wetness: 0.2, isPaired: 0.1, suitedness: 0.1, connectivity: 0.2 },
  },
};

/**
 * Score how typical a board is within its archetype (0-1).
 * 1.0 = perfectly typical (right at centroid), 0.0 = very atypical.
 *
 * Uses weighted Euclidean distance from the archetype centroid,
 * scaled by per-feature tolerance.
 */
export function scoreBoardTypicality(
  archetypeId: ArchetypeId,
  boardFeatures: BoardFeatures,
): number {
  const centroid = ARCHETYPE_CENTROIDS[archetypeId];
  if (!centroid) return 0.5; // Unknown archetype — assume moderate

  const { center, tolerance } = centroid;
  const keys: (keyof BoardFeatures)[] = [
    "highCardNorm", "wetness", "isPaired", "suitedness", "connectivity",
  ];

  let totalDist = 0;
  for (const key of keys) {
    const diff = Math.abs(boardFeatures[key] - center[key]);
    const tol = Math.max(tolerance[key], 0.01); // avoid div by zero
    const normalizedDiff = diff / tol;
    totalDist += normalizedDiff ** 2;
  }

  // RMS distance, then convert to 0-1 score (Gaussian falloff)
  const rmsDist = Math.sqrt(totalDist / keys.length);
  return Math.exp(-0.5 * rmsDist ** 2);
}

/**
 * Practical impact assessment — translates abstract accuracy into
 * what it actually means for the user's poker decisions and EV.
 */
export interface AccuracyImpact {
  /** Estimated accuracy 0-1 */
  accuracy: number;
  /** Human label: "Very High" | "High" | "Moderate" | "Approximate" */
  label: string;
  /** Detailed description for the user */
  description: string;
  /** Estimated max EV impact in BB per decision from the accuracy gap */
  maxEvImpactBB: number;
  /** Whether the accuracy gap could change the "optimal" action */
  couldFlipOptimal: boolean;
  /** Plain-language "what this means" for a poker player */
  practicalMeaning: string;
}

/**
 * Estimate how accurate the archetype frequency is for a specific board,
 * AND what that accuracy gap means in practical poker terms.
 *
 * The key insight: accuracy gaps matter very differently depending on
 * how close the top two actions are in frequency.
 *
 * - Clear spots (one action dominates 60%+): accuracy gap is invisible.
 *   Even a 10% shift doesn't change the user's decision.
 * - Close spots (top actions within 10% of each other): accuracy gap
 *   could flip which action appears "optimal," but both are GTO-correct
 *   because the solver MIXES between them.
 *
 * @param archetypeAccuracy - Archetype-level accuracy metrics
 * @param boardTypicality - How typical this board is (0-1, from scoreBoardTypicality)
 * @param potSizeBB - Current pot size in big blinds (for EV impact calculation)
 * @param topActionGap - Gap between the two highest-frequency actions (0-1).
 *   If undefined, uses a conservative estimate from the accuracy data.
 */
export function estimateBoardAccuracy(
  archetypeAccuracy: ArchetypeAccuracy,
  boardTypicality: number,
  potSizeBB?: number,
  topActionGap?: number,
): AccuracyImpact {
  // Board accuracy = archetype accuracy × typicality weighting
  // Typical boards get full archetype accuracy; atypical boards get discounted
  const accuracy = archetypeAccuracy.accuracy * (0.5 + 0.5 * boardTypicality);
  const clamped = Math.max(0, Math.min(1, accuracy));
  const pct = Math.round(clamped * 100);
  const gap = 1 - clamped; // e.g. 0.04 for 96% accuracy

  // ── EV impact calculation ──
  // The accuracy gap (stdDev) tells us how much the frequency could shift.
  // EV impact = frequency_shift × pot × decision_sensitivity
  // Decision sensitivity depends on how close the top actions are:
  // - If one action is clearly best (60%+ frequency), shifting by 4% changes nothing
  // - If two actions are 50/50, shifting by 4% could matter but EV diff is tiny
  const pot = potSizeBB ?? 10; // default 10BB pot
  const frequencyUncertainty = archetypeAccuracy.avgStdDev;

  // Maximum EV impact: if you pick the wrong action due to the gap,
  // you lose roughly (stdDev × pot × 0.5). The 0.5 factor accounts for
  // the fact that when frequencies are close, EV between actions is also close.
  const maxEvImpactBB = Math.round(frequencyUncertainty * pot * 0.5 * 100) / 100;

  // Could the gap flip the optimal action?
  // Only if the top-action gap is smaller than 2× the frequency uncertainty
  const effectiveGap = topActionGap ?? 0.15; // conservative: assume moderate gap
  const couldFlipOptimal = effectiveGap < frequencyUncertainty * 2;

  // ── Labels and descriptions ──
  let label: string;
  let description: string;
  let practicalMeaning: string;

  if (pct >= 95) {
    label = "Very High";
    description = `Solver analysis of ${archetypeAccuracy.boardCount} similar boards shows very consistent strategy. This board is highly typical — estimated accuracy ~${pct}%.`;
    practicalMeaning = maxEvImpactBB < 0.1
      ? "The accuracy gap has zero practical impact on your decisions. Play exactly as shown."
      : `At most ~${maxEvImpactBB} BB per decision in a ${pot} BB pot. The recommended action is reliable.`;
  } else if (pct >= 88) {
    label = "High";
    description = `Based on ${archetypeAccuracy.boardCount} solver runs. This board fits the pattern well — estimated accuracy ~${pct}%.`;
    practicalMeaning = couldFlipOptimal
      ? `Close spot — the top actions are similar in EV. Both are correct; the "best" one might differ by ~${maxEvImpactBB} BB in a ${pot} BB pot.`
      : `Clear spot — the recommended action is right. The gap costs at most ~${maxEvImpactBB} BB in a ${pot} BB pot.`;
  } else if (pct >= 75) {
    label = "Moderate";
    description = `Frequencies vary across similar boards. This board has some atypical features — estimated accuracy ~${pct}%. Board-specific details may shift frequencies.`;
    practicalMeaning = `Frequencies could shift ±${Math.round(frequencyUncertainty * 100)}% on the exact board. In a ${pot} BB pot, that's up to ~${maxEvImpactBB} BB. Use the direction, not the exact numbers.`;
  } else {
    label = "Approximate";
    description = `This board is at the edge of the pattern — estimated accuracy ~${pct}%. The exact solver answer may differ meaningfully. Treat frequencies as directional guidance.`;
    practicalMeaning = `This spot varies significantly across boards in this category. In a ${pot} BB pot, the EV gap could be ~${maxEvImpactBB} BB. Focus on the general principle rather than exact frequencies.`;
  }

  return {
    accuracy: clamped,
    label,
    description,
    maxEvImpactBB,
    couldFlipOptimal,
    practicalMeaning,
  };
}

/**
 * Compute the gap between the top two actions in a frequency distribution.
 * Used as input to estimateBoardAccuracy for precise impact assessment.
 *
 * @returns Gap between the highest and second-highest frequency (0-1).
 *   Returns 1.0 if only one action exists.
 */
export function computeTopActionGap(frequencies: ActionFrequencies): number {
  const values = Object.values(frequencies)
    .filter((v): v is number => v !== undefined && v > 0.001)
    .sort((a, b) => b - a);

  if (values.length <= 1) return 1.0;
  return values[0] - values[1];
}

// ═══════════════════════════════════════════════════════
// SAMPLE SIZE ANALYSIS — how many more boards do we need?
// ═══════════════════════════════════════════════════════

/**
 * Projection of what more solver boards would buy for an archetype.
 */
export interface SampleSizeProjection {
  /** Current number of boards */
  currentBoards: number;
  /** Current average standard error across all actions */
  currentStdError: number;
  /** Current max EV impact (BB) at a reference pot size */
  currentMaxEvBB: number;
  /** Projections at various board counts */
  projections: {
    boards: number;
    stdError: number;
    maxEvBB: number;
    /** Improvement vs current (0-1, e.g. 0.30 = 30% tighter) */
    improvement: number;
    /** Marginal improvement per additional board (diminishing returns indicator) */
    marginalGainPerBoard: number;
  }[];
  /** Recommended sweet spot: board count where marginal returns drop below threshold */
  sweetSpot: number;
  /** Whether current data is already "good enough" (stdError < 0.01) */
  sufficientlyPrecise: boolean;
  /** Human summary */
  summary: string;
}

/**
 * Analyze how many more boards an archetype needs to reach a target precision.
 *
 * Uses the statistical relationship: stdError = stdDev / √n
 * More boards reduce the standard error of the mean (how confident we are
 * in the average frequency), but with diminishing returns (√n).
 *
 * @param currentBands - Current frequency bands from solver output
 * @param currentBoards - How many boards are currently solved
 * @param refPotBB - Reference pot size for EV impact (default 10 BB)
 * @returns Projection with sweet spot recommendation
 */
export function analyzeSampleSize(
  currentBands: PositionFrequencyBands,
  currentBoards: number,
  refPotBB: number = 10,
): SampleSizeProjection {
  // Collect all stdDevs from current band data
  const stdDevs: number[] = [];
  for (const actionBands of Object.values(currentBands)) {
    if (!actionBands) continue;
    for (const band of Object.values(actionBands)) {
      if (band && band.sampleCount >= 2) {
        stdDevs.push(band.stdDev);
      }
    }
  }

  if (stdDevs.length === 0) {
    return {
      currentBoards,
      currentStdError: 0,
      currentMaxEvBB: 0,
      projections: [],
      sweetSpot: currentBoards,
      sufficientlyPrecise: true,
      summary: "No variance data available — cannot project sample size needs.",
    };
  }

  // Average population stdDev (this is inherent to the archetype, not reducible)
  const avgPopStdDev = stdDevs.reduce((a, b) => a + b, 0) / stdDevs.length;
  // Max population stdDev (worst-case action)
  const maxPopStdDev = Math.max(...stdDevs);

  // Current standard error of the mean
  const currentStdError = avgPopStdDev / Math.sqrt(currentBoards);
  const currentMaxEvBB = Math.round(currentStdError * refPotBB * 0.5 * 100) / 100;

  // Project forward
  const targetBoards = [25, 40, 50, 75, 100, 150, 200, 300, 500];
  const projections = targetBoards
    .filter(n => n > currentBoards) // only show future projections
    .map(boards => {
      const stdError = avgPopStdDev / Math.sqrt(boards);
      const maxEvBB = Math.round(stdError * refPotBB * 0.5 * 100) / 100;
      const improvement = 1 - stdError / currentStdError;

      // Marginal gain: improvement per additional board from previous step
      const prevBoards = boards === targetBoards.filter(n => n > currentBoards)[0]
        ? currentBoards
        : targetBoards.filter(n => n > currentBoards && n < boards).pop() ?? currentBoards;
      const prevStdError = avgPopStdDev / Math.sqrt(prevBoards);
      const marginalGainPerBoard = (prevStdError - stdError) / (boards - prevBoards);

      return { boards, stdError, maxEvBB, improvement, marginalGainPerBoard };
    });

  // Find sweet spot: where marginal gain per board drops below 0.0001
  // (i.e., each additional board improves stdError by less than 0.01%)
  const MARGINAL_THRESHOLD = 0.00005;
  let sweetSpot = currentBoards;
  for (const p of projections) {
    if (p.marginalGainPerBoard > MARGINAL_THRESHOLD) {
      sweetSpot = p.boards;
    } else {
      break;
    }
  }
  // If no projection crosses the threshold, the smallest projection is sufficient
  if (sweetSpot === currentBoards && projections.length > 0) {
    sweetSpot = projections[0].boards;
  }

  const sufficientlyPrecise = currentStdError < 0.01; // < 1% standard error

  // Build summary
  let summary: string;
  if (sufficientlyPrecise) {
    summary = `Already precise at ${currentBoards} boards (std error ${(currentStdError * 100).toFixed(1)}%). More boards would have negligible impact. The frequencies shown are reliable to ±${(currentStdError * 100).toFixed(1)}%.`;
  } else {
    const sweetProj = projections.find(p => p.boards === sweetSpot);
    const sweetEv = sweetProj?.maxEvBB ?? currentMaxEvBB;
    const additionalNeeded = sweetSpot - currentBoards;
    summary = `Current: ${currentBoards} boards, ±${(currentStdError * 100).toFixed(1)}% uncertainty (~${currentMaxEvBB} BB EV impact in ${refPotBB} BB pot). Sweet spot: ${sweetSpot} boards (+${additionalNeeded} more) would narrow to ±${((avgPopStdDev / Math.sqrt(sweetSpot)) * 100).toFixed(1)}% (~${sweetEv} BB). Beyond ${sweetSpot} boards: diminishing returns.`;
  }

  return {
    currentBoards,
    currentStdError,
    currentMaxEvBB,
    projections,
    sweetSpot,
    sufficientlyPrecise,
    summary,
  };
}

/**
 * Quick check: for a given population stdDev and current n,
 * how many total boards to reach a target stdError?
 *
 * Formula: n = (stdDev / targetStdError)²
 */
export function boardsNeededForPrecision(
  populationStdDev: number,
  targetStdError: number,
): number {
  if (targetStdError <= 0) return Infinity;
  return Math.ceil((populationStdDev / targetStdError) ** 2);
}

// ═══════════════════════════════════════════════════════
// SOLVER OUTPUT → FREQUENCY TABLE MAPPING
// ═══════════════════════════════════════════════════════

/**
 * Raw solver output format (from batch_solve.py parse).
 * Categories use solver naming which mostly matches HandCategory
 * but has some differences (e.g. "underpair" → "bottom_pair").
 */
export interface SolverOutput {
  archetypeId: string;
  boardsAnalyzed: number;
  context: {
    street: string;
    potType: string;
    heroPosition: string;
    villainPosition: string;
  };
  ip_frequencies: Record<string, Record<string, number>>;
  oop_frequencies: Record<string, Record<string, number>>;
  actions_ip: string[];
  actions_oop: string[];
}

/** Map solver hand categories to our HandCategory type */
const SOLVER_CATEGORY_MAP: Record<string, HandCategory> = {
  // Direct matches
  sets_plus: "sets_plus",
  two_pair: "two_pair",
  overpair: "overpair",
  top_pair_top_kicker: "top_pair_top_kicker",
  top_pair_weak_kicker: "top_pair_weak_kicker",
  middle_pair: "middle_pair",
  bottom_pair: "bottom_pair",
  flush_draw: "flush_draw",
  straight_draw: "straight_draw",
  combo_draw: "combo_draw",
  overcards: "overcards",
  air: "air",
  // Solver-specific mappings
  underpair: "bottom_pair",   // Underpair maps to bottom_pair category
};

/** Map solver action names to our GtoAction type */
const SOLVER_ACTION_MAP: Record<string, GtoAction> = {
  check: "check",
  fold: "fold",
  call: "call",
  bet_small: "bet_small",
  bet_medium: "bet_medium",
  bet_large: "bet_large",
};

/**
 * Convert raw solver output to our FrequencyTable format.
 * Merges solver categories into HandCategory (e.g. underpair → bottom_pair).
 */
export function solverOutputToTable(
  raw: SolverOutput,
  metadata: {
    name: string;
    description: string;
    keyPrinciple: string;
    commonMistakes: string[];
  },
): FrequencyTable {
  return {
    archetypeId: raw.archetypeId as ArchetypeId,
    name: metadata.name,
    description: metadata.description,
    context: {
      street: raw.context.street as FrequencyTable["context"]["street"],
      potType: raw.context.potType as FrequencyTable["context"]["potType"],
      heroPosition: raw.context.heroPosition,
      villainPosition: raw.context.villainPosition,
    },
    ipFrequencies: mapPositionFrequencies(raw.ip_frequencies),
    oopFrequencies: mapPositionFrequencies(raw.oop_frequencies),
    actionsIp: raw.actions_ip.map(mapAction).filter(Boolean) as GtoAction[],
    actionsOop: raw.actions_oop.map(mapAction).filter(Boolean) as GtoAction[],
    boardsAnalyzed: raw.boardsAnalyzed,
    keyPrinciple: metadata.keyPrinciple,
    commonMistakes: metadata.commonMistakes,
    source: `TexasSolver (${raw.boardsAnalyzed} boards)`,
  };
}

function mapPositionFrequencies(
  raw: Record<string, Record<string, number>>,
): PositionFrequencies {
  const result: PositionFrequencies = {};

  for (const [solverCat, freqs] of Object.entries(raw)) {
    const handCat = SOLVER_CATEGORY_MAP[solverCat];
    if (!handCat) continue;

    const mapped: ActionFrequencies = {};
    for (const [action, prob] of Object.entries(freqs)) {
      const gtoAction = SOLVER_ACTION_MAP[action];
      if (gtoAction && prob > 0.0001) {
        mapped[gtoAction] = prob;
      }
    }

    // Merge if category already exists (e.g. underpair + bottom_pair)
    if (result[handCat]) {
      const existing = result[handCat]!;
      for (const [action, prob] of Object.entries(mapped)) {
        const key = action as GtoAction;
        existing[key] = ((existing[key] ?? 0) + (prob ?? 0)) / 2;
      }
    } else {
      result[handCat] = mapped;
    }
  }

  return result;
}

function mapAction(solverAction: string): GtoAction | null {
  return SOLVER_ACTION_MAP[solverAction] ?? null;
}
